services:
  postgres:
    image: postgres:18
    container_name: pg18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database/pgdata:/var/lib/postgresql
      - ./database/init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    volumes:
      - ./backend:/app